version: "3.8"

services: 
  ipfs:
    container_name: ipfs_host
    image: ipfs/go-ipfs:master-latest
    volumes: 
    - "./tmp:/tmp"
    ports:
    - "5001:5001" # internal API
    - "4001:4001" # expose to public
    - "8088:8080" # web gateway