apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pastebin-ipfs
  name: pastebin-ipfs
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: pastebin-ipfs
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3939'
        prometheus.io/path: '/metrics'
      labels:
        app: pastebin-ipfs
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: pastebin-ipfs
        ports:
          - name: web
            containerPort: 3939
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        command: {{- toYaml .Values.command | nindent 8 }}
      - image: ipfs/go-ipfs:v0.10.0
        name: ipfs-daemon
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
          