apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  labels:
    app: pastebin-ipfs
  name: pastebin-ipfs
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: / 
        backend:
          serviceName: pastebin-ipfs
          servicePort: 3939
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.secretName }}
