openapi: 3.0.0
info:
  version: "0.0.1"
  title: "Pastbin-IPFS API"
  
servers:
  - url: https://paste.shoujo.io/api/v0
    description: Production server
  - url: http://localhost:3939/api/v0
    description: Local testing server
paths:
  /gallery:
    get:
      summary: Returns a list of recent published cid.
      responses:
        '200':    # status code
          description: A JSON array of cid
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
                  
  /upload:
    post:
      summary: Create a resource.
      requestBody:
        content: 
          multipart/form-data: # Media type
            schema:            # Request payload
              type: object
              properties:      # Request parts
                author:        # Optional   
                  type: string
                encrypt_algorithm: # Optional 
                  type: string
                file:  # Data
                  type: string
                  format: binary
      responses:
        '201':    # status code
          description: Parent cid
          content:
            application/json:
              schema: 
                type: string
                
  /{cid}/{file}:
    get:
      summary: Returns file content.
      parameters:
        - name: cid
          in: path
          description: cid
          required: true
          schema:
            type: string
        - name: file
          in: path
          description: file fullname
          required: true
          schema:
            type: string
      responses:
        '200':    # status code
          description: File content
          content:
            text/plain:
              schema: 
                type: string
        '404':
          description: File not found
          