name: Deploy

on:
  push:
    tags:
      - v*
  release:
    types:
      - published
      - released

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          script: |
            cd pastebin-ipfs
            git pull
            cd deploy/docker
            docker-compose pull   
            docker-compose up -d
